version: "3.0"
services:
  DriveX_bot:
    container_name: DriveX_bot
    image: drive_x_bot # Specify the name of the Docker image to be built
#    environment:

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge