USER_DATA_ATTEMPTS = 480
SUBSCRIBE_ACK_ATTEMPTS = 480
PAUSE_BETWEEN_REQUESTS = 180


USER_DATA_ENDPOINT = "https://drivex.fun/Telega/AddUserData"
SUBSCRIBE_ACK_ENDPOINT = "https://drivex.fun/Telega/UserSubscribed"
